version: "3"

services:
  flask:
    build: ./server
    volumes:
     - /home/saankhyalabs/videos:/home/saankhyalabs/videos
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
